<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\.stylecop\StyleCop.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>MetaOptimize.Cli.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Google.OrTools" />
    <PackageReference Include="Gurobi.Optimizer" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
    <PackageReference Include="QuikGraph" />
    <PackageReference Include="ZenLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetaOptimize\MetaOptimize.csproj" />
  </ItemGroup>
</Project>